apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking-kind-network-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
    targetRevision: main
    path: apps/overlays/networking-kind/network-lab-frr
  destination:
    server: https://kubernetes.default.svc
    namespace: network-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
