apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-lab-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
    targetRevision: main
    path: bootstrap
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true