apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-k3s-crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 1.16.0
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/apps/overlays/crossplane-k3s/crossplane/values.yaml
    - repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
