---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgATkp8yg5D+k590hw+m68Q90VBJoGCiKupn2feKzNGYGeu1m3/OmVMOx7PApbVfRnIG10+3zabYzXVdU3Dl3LD56FrjceLckBEOONGQ//Wt+Nx+0xAB+3e/jrt/7jDeC/9mhbhi61ZnFkavH+WUB7dM6eIBbAdAHA9+RXLuky6LouEy18ZnjsNuakC4lkRrSA4SehWGXcMB477lSLN2PtGdmp9+AF6h9q/fvFdwBT7vT5MesOK7tFwNbc8hsVJIfnkuEP30EDqinnTGoACo5eDq3iYQquZSfyP2Xcvu+Q73xK3U0hWuOW2Va1ym71W+mLrNZV3fpD8iRaFbH4mltd6qtAZsDqlPBiyNvPpAG3pUmNPgGMYghCs1Sdye6J7XiEEX39Z2tHvbfSReoOEfhocDFQwxhfIyXkGJMCdjSy19eOGTaWdSNoCG/zRjXc/HAKvvtgg2qW7D7JVQtH9kyEO9+r558SOk9BvgVUiPpdFw+1OsvXkKFLzm8tvAnFuehzX/+dfcZ2N0O5NMnef7Zk9mNUNlSHos45CoAOowdGy+V/eOuJ2vjTLW2rI0hrXM5/wEMUEU1HdI8ewmyoFHi9jGR/WW58eyQibE7LGwoHyONZs017qalK6Vvn6Cpkte30fR46aLMRQTzW4l5vph14bJezJ9cFuiKxCUH9ZVj9CmOQwEwAzPBJkLoAsWpv2QZKjMxEVZy3OgyRWTf6oh6F8UNq0pIUJ4sO/zaeE6D3bS5JyjdfHK7icChI7T09xaxg3NG72hQsxO+DjYrRs=
    admin.passwordMtime: AgBlgES/+wYNj7LfidGRk8PmjQIKSgrDMdJvAl1WGWJC5SRQkh6M1a656AKfCUjkA8+FSitFF5u5jEBO78MvRSwxJM6qably2hAXUe6GLzM90LQLRAt23nnubOmv0pGazCoXY4KhVbxA6XhGBKqaCY7XM+s7SBL+AalMeJEEKJ+aumlcF6fH3J53O4nXmZMYjlo55Zp0wY90P1BshynIUUyUgNlZXEwVklJIHd82mxo8lJBb0kBFzzs+RkyoBNyfhj/BVyQ+G+/Bmje5CkTfHtAIjhqlFQZ8hcfA+M2Ljk6MkjE+ig5A+Ko2sk+rsTawvHnPRZDvfV3VqksbByWvVaD5pw7Er/k3Tj5igOBFEANM/+wE+7S2dtYabegC4a/DpV6U1Gt5WieRncbJbvNPvTPON7Ew7Jf7UZ6164/2ecn4yi3C/OixF8S5KgBcPy8OvdVbnI5oaFx+dtuxBjPWarWlLxp8INymkOcqkC4Kfw60g9MhRLF+qISe44LyK4faw5z5ko8IJdfTuX3mamLeZxZQgmWVbkTlY0CzyOST92RuF25rHzw9C0EbbKXzR4Wxa/oodZS0siqZ7g72HJS6o6M21htQ605ZLLOPVl1flNxv8uOW5DOOlUwrSWbk1dY1XE+y8H4o1p7AXVbDxvIrGakH7T4vZwVGbr4ntaQ5GhU5b01wdZr9o/OvNgWPWC7UpmgGtB5Kzv+zQZMRIsOe2Kna0/pLg6HH
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
