apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-k3d-blackbox-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      targetRevision: 11.8.0
      helm:
        releaseName: blackbox-exporter
        valueFiles:
          - $values/apps/overlays/observability-k3d/monitoring/blackbox-values.yaml
    - repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
