apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: "1.15"
      helm:
        releaseName: cilium
        valueFiles:
          - $values/apps/overlays/observability-k3d/cilium/values.yaml
    - repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true