apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-k3d-monitoring-probes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonardocastanodiaz/ingress-lab.git
    targetRevision: main
    path: apps/overlays/observability-k3d/monitoring/probes
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
