apiVersion: v1
kind: ConfigMap
metadata:
  name: frr1-config
  namespace: network-lab
data:
  daemons: |
    zebra=yes
    bgpd=yes
  vtysh.conf: |
    service integrated-vtysh-config
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname frr1
    log stdout

    router bgp 65001
      bgp router-id 1.1.1.1
      !
      address-family ipv4 unicast
        network 10.1.0.0/24
      exit-address-family
    !
    line vty
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frr1
  namespace: network-lab
  labels:
    app: frr1
spec:
  serviceName: frr1
  replicas: 1
  selector:
    matchLabels:
      app: frr1
  template:
    metadata:
      labels:
        app: frr1
    spec:
      containers:
        - name: frr
          image: frrouting/frr:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    for i in $(seq 1 30); do
                      vtysh -f /etc/frr/frr.conf >/dev/null 2>&1 || true
                      if vtysh -c "show bgp summary" >/dev/null 2>&1; then
                        break
                      fi
                      sleep 2
                    done
                    NEIGHBOR_IP="$(getent hosts frr2-0.frr2.network-lab.svc.cluster.local | awk '{print $1}' | head -n1)"
                    if [ -n "$NEIGHBOR_IP" ]; then
                      vtysh \
                        -c "conf t" \
                        -c "router bgp 65001" \
                        -c "neighbor ${NEIGHBOR_IP} remote-as 65002" \
                        -c "neighbor ${NEIGHBOR_IP} ebgp-multihop 2" \
                        -c "neighbor ${NEIGHBOR_IP} disable-connected-check" \
                        -c "neighbor ${NEIGHBOR_IP} timers 3 9" \
                        -c "neighbor ${NEIGHBOR_IP} soft-reconfiguration inbound" \
                        -c "end" || true
                    fi
                    exit 0
          volumeMounts:
            - name: frr-config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: frr-config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
            - name: frr-config
              mountPath: /etc/frr/vtysh.conf
              subPath: vtysh.conf
          ports:
            - name: bgp
              containerPort: 179
      volumes:
        - name: frr-config
          configMap:
            name: frr1-config
---
apiVersion: v1
kind: Service
metadata:
  name: frr1
  namespace: network-lab
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: frr1
  ports:
    - name: bgp
      port: 179
      targetPort: 179
