apiVersion: v1
kind: ConfigMap
metadata:
  name: frr1-config
  namespace: network-lab
data:
  daemons: |
    zebra=yes
    bgpd=yes
  vtysh.conf: |
    service integrated-vtysh-config
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname frr1
    log stdout

    router bgp 65001
      bgp router-id 1.1.1.1
      neighbor frr2.network-lab.svc.cluster.local remote-as 65002
      neighbor frr2.network-lab.svc.cluster.local timers 3 9
      neighbor frr2.network-lab.svc.cluster.local soft-reconfiguration inbound
      !
      address-family ipv4 unicast
        network 10.1.0.0/24
      exit-address-family
    !
    line vty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frr1
  namespace: network-lab
  labels:
    app: frr1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frr1
  template:
    metadata:
      labels:
        app: frr1
    spec:
      containers:
        - name: frr
          image: frrouting/frr:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: frr-config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: frr-config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
            - name: frr-config
              mountPath: /etc/frr/vtysh.conf
              subPath: vtysh.conf
          ports:
            - name: bgp
              containerPort: 179
      volumes:
        - name: frr-config
          configMap:
            name: frr1-config
---
apiVersion: v1
kind: Service
metadata:
  name: frr1
  namespace: network-lab
spec:
  selector:
    app: frr1
  ports:
    - name: bgp
      port: 179
      targetPort: 179
