apiVersion: v1
kind: ConfigMap
metadata:
  name: frr2-config
  namespace: network-lab
data:
  daemons: |
    zebra=yes
    bgpd=yes
  vtysh.conf: |
    service integrated-vtysh-config
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname frr2
    log stdout

    router bgp 65002
      bgp router-id 2.2.2.2
      no bgp ebgp-requires-policy
      !
      address-family ipv4 unicast
        network 10.2.0.0/24
      exit-address-family
    !
    line vty
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frr2
  namespace: network-lab
  labels:
    app: frr2
spec:
  serviceName: frr2
  replicas: 1
  selector:
    matchLabels:
      app: frr2
  template:
    metadata:
      labels:
        app: frr2
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"sriov-net-emulated","interface":"net1","ips":["172.30.0.12/24"]}]'
    spec:
      containers:
        - name: frr
          image: frrouting/frr:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    set -eu

                    PEER_DNS="frr1-0.frr1.network-lab.svc.cluster.local"
                    PEER_ASN="65001"
                    LOCAL_ASN="65002"
                    MAX_RETRIES=60
                    STATIC_PEER_IP="172.30.0.11"
                    TARGET_PEER_IP="${STATIC_PEER_IP}"

                    vtysh -f /etc/frr/frr.conf >/dev/null 2>&1 || true

                    for i in $(seq 1 "${MAX_RETRIES}"); do
                      if vtysh -c "show bgp summary" >/dev/null 2>&1; then
                        break
                      fi
                      sleep 2
                    done

                    if ! ip -4 addr show dev net1 >/dev/null 2>&1; then
                      TARGET_PEER_IP=""
                      for i in $(seq 1 "${MAX_RETRIES}"); do
                        TARGET_PEER_IP="$(getent hosts "${PEER_DNS}" | awk '{print $1}' | head -n1 || true)"
                        if [ -n "${TARGET_PEER_IP}" ]; then
                          break
                        fi
                        sleep 2
                      done
                    fi

                    if [ -z "${TARGET_PEER_IP}" ]; then
                      echo "failed to resolve peer ${PEER_DNS} and no multus interface found"
                      exit 1
                    fi

                    for OLD_PEER_IP in $(vtysh -c "show running-config" | awk '/neighbor [0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+ remote-as 65001/{print $2}'); do
                      if [ "${OLD_PEER_IP}" != "${TARGET_PEER_IP}" ]; then
                        vtysh -c "conf t" -c "router bgp ${LOCAL_ASN}" -c "no neighbor ${OLD_PEER_IP} remote-as ${PEER_ASN}" -c "end" || true
                      fi
                    done

                    vtysh \
                      -c "conf t" \
                      -c "router bgp ${LOCAL_ASN}" \
                      -c "no bgp ebgp-requires-policy" \
                      -c "neighbor ${TARGET_PEER_IP} remote-as ${PEER_ASN}" \
                      -c "neighbor ${TARGET_PEER_IP} ebgp-multihop 2" \
                      -c "neighbor ${TARGET_PEER_IP} disable-connected-check" \
                      -c "neighbor ${TARGET_PEER_IP} timers 3 9" \
                      -c "neighbor ${TARGET_PEER_IP} soft-reconfiguration inbound" \
                      -c "address-family ipv4 unicast" \
                      -c "neighbor ${TARGET_PEER_IP} activate" \
                      -c "exit-address-family" \
                      -c "end"
          volumeMounts:
            - name: frr-config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: frr-config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
            - name: frr-config
              mountPath: /etc/frr/vtysh.conf
              subPath: vtysh.conf
            - name: captures
              mountPath: /captures
          ports:
            - name: bgp
              containerPort: 179
      volumes:
        - name: frr-config
          configMap:
            name: frr2-config
  volumeClaimTemplates:
    - metadata:
        name: captures
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: frr2
  namespace: network-lab
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: frr2
  ports:
    - name: bgp
      port: 179
      targetPort: 179
