---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAH2rxFIZBdVEQaW2GimJbsv1Gyt0YCnqR1fMHUwwi8gdcZWqLZewtxgVS3OnpVuNzPoigIXg+/6s3ZdQDagVqLSw0shYs3Wo934VJES0aI4GfWDlZzFEhgjjJPa/6qmfkmqSeDWS5OLtFLrIAeMup9Jrfv7XtLmR8QjtLYkFoPrp39ls5GljIlqnXRJSIH4+32Q6dx/nTi4o6j0d/fyQqL1ABSRLI9hDaI4cqJYunz+u1Rtdbs+zazQ3G4JA8He/4/yZ9tOnWMDeh/RPjf07pD5B0TKRs1jihgAM5pqHQBdoWbQ2/h0vijcCcatQIxsna/K+eoeadCdbqYSUrhmdluy5wfHsnPJpeW9ZX3+ESewGkEoDCNWu92JmFpewdZnQoFns7n36zNf6hRrLlIu/Bztngwsa8lQjXusq240gnYsPtC+GI8pj92koIHYeG+hDKsf+U8Z83zYcVlNJeB/8H2itQgJCpo/X01mxCXPf5iZ5RdWUamgeWNS4ByQefGJR4k05rHIFyf+5Uz7YGS5vTNdD3R5PRn5HmS2wl/6yZoUMrsE1FYkzJUYwStUy/X7posLqyWHasxZ7s+f5XVneWk6CSTQwT8mYXdWtqQMK6axwRFxYowDrcTjoaqdEkJY050tkN/p1xOBHSsUAQnlPFACg6M15gu856LK2bZKIuiRii4V+gbynQadB9EeG5GC7bGUAgGMZDvH8v1OLo7CDYpOk1TJaddzR9PJx4+NWPM+xo8EXcfBn/0X6teo7meMghRH9xOUhNBkA1Ek38=
    admin.passwordMtime: AgCR97ta57cWLo9+iF+1cMQV2DTDKJRA+ni7KFYW4NsgAUznYiAa3amTUQ9iM1oDiyE5kLZlyOKPjQ/gYp7tCkUbvMS6K5wYlhGt5E2/D4CTyGw8hyVZI7kUK7vDMGoOXphV9EDymKvw/BTrHB/gaoMS3CTfh2y7V58ppXaJ4AhpKW1Bfx49SRzSCS+XZXpBWht9UQwijrRnBU2OWx1KBaT01SeNWzAi6c7zPYeoiISrg/Ixoi1Whc+dOqDBaI/3qLzBOJMOzn2jSjWluAX8uNJln4YoUxOxvNu/haWAWnUswVEkSBimHDDTQ+XouvRu8t3o23rN3EBjkfpn0pquJyQpRhKv4VAm38ko1oD/kGX/TqRN65FFnFz8gQIvNs3i404ivXReBYn/E+2VTYiGFjTgHIQMcII9VlGBb8C5yTpwq4nk92TpgFYkfl9vSWoSMEWOKQtR2F/hLqLX8BwmJXD0CuTEAmhdzc6Uqvgru8KXyii+8gB13uLNZChPpq3SYXgsMtHeW0F4fV4JM+o5lJOT6DA73Doz8f9uc02Qvu1cgDumW4RnJh3mxoapx+MLiDbjO5nX5o/of/2XC0Om2pq5MgCbDt1uh10nf5YJxyKYfHsr+bLGZa5kZupmYDKiSiMGU/1uCkqVh5aSFKHrNdC93dauq08QOoMHmuOyTFE0bycBlrOeDQlX4SI044lBo7F3bNfVZGCNCzAUGZQqav2XqDu6YD/O
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
