---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: observability-monitoring
spec:
  encryptedData:
    admin-password: AgBNPqwP3NfOEkxkJLlz6e+fuaYeCEkw1CAJnpq0kT5THbV/ZSoEmUsQbcW5syJCplWkdl8QTQDc3CxU0JzbXQKWmiui9bBCQcsEjyFiOjj97yu9YWu4dFJpg90YEnTxStXMPPxYTYiZl39sYxko7DtJwlKZX9ZKKg6oBNfWIGVZpeSMNo9/MizwGlV7w0hPbih178TKRWZIwTeVdCzfRMDRSkNOw+U3Pw9LamVOEF3ddkppPVDTEkRqHbVEWQUBdzB5dkErgywkDHyXX2UGFv92L9320+b9L+CyTTemu5VkrltmMeVinfQAwyUwEpSYjQ5WazH7/HPtj5+w5nfuJlr6u0X4HnWTcRp4YGKR1VfaPyTl4X6ndG54C/yGFfhOun/YiXrGzZrRZI0Vo+elBtezZJpWdLF7e6P1fPmrK+tqMpGQU22w9vPteYH81fhKFLJ14TE9j0oFjX3/YzVHD/d5alijwMQGbmHczRxY3YT2CuFXcv0dv8kn/rJI+IWCiGHTmPHh4sHnvWV7G/Leg+kBkpc+e4eBzbtT3VDSzDEWXMbbFaeBx/KLy4bpr4bX520oEOZcEHhLg0Ko0VX0ho4iuImKp2kZDIAswoWPB8JjHN3HH8zDVrDVvvBqm7ZGTKvb9iyQRvNZ3rKiRnhIS1v7LETfJh8tQWtPhUs8VtfkO6RRPIu907lITcbzWaSmXf6Iod545arGKA==
    admin-user: AgBcUzPXb9sRfI48FGu9SXTpkUmZkKDe5rswaf6MBllzxQYrxYz7SM3rWg7BJVIZx703DcVT54yVmIEmYD8vLnECzi6YX9bbC00imlx7YIEUGJXpleBVG3sz3MXlcyyc3jzX33jUBdIxKkD13karj5/XZAVPKwi7OkPWoNolwRe9YMrSrCGE1GHYAnd58JUJTi+KrIoqkRvR2NXTsNuqz/blU+Yqa+xA/w/lm8OS6GQ8FapfW1p6NxVPzbHmandodSzw3T9BLEvApNRfmDV4qD8Y+uWztXzGYIaf3zTzFr99QRh2JJVPoq7bFRu5wb+wMP6k4XrmfKkOMO1vKIzlXA8aemoHLoQpWl8nrhJhqqAMZIzv9clP87eMvEcQgvlnxIWcOAErnfuXqGd/zxrjxsAE1A7viLxOASaG1Rv4ThF3d87+QFuSvWGW8NGVXXuruREZhaI19UAVU4aS5I8e8yUqfZv/r9cDizPJJafJ2O4Sr41LgR03hiyIh2SqDw+zfhxTDeCSZwwH3v3omTB+DB95AqOFszTqGOcvfcKJuy+XiEXfLsoRpQhvbKVNaRz110Ko2vzrU4vlbLHhERsGtM893Go4klBrVNNkRXCKGdD6oE6sEbxd0xVdZUxiqICVRhl/cBod1i+LrM7Ld+SkkggZGM6dVWDQOBpjNQDLjEvZYkafBzHt24FLpahXCD/tUfN5qxDM0w==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: observability-monitoring
