apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"
  server.extraArgs: "--grpc-web"
  url: "http://argocd.observability.local:8080"
  users.session.duration: "24h"
