---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBoMY0bjqmUAbD10VaQLQ1fKyuAxJT5SBC00q7A2qQTieKtYlYp9GiagfU2SuQuHgd5CFs7NN2n1XOX5ZyosEK+8uk3Tr9VlvGZM6+rKpbNpwcFQIZk8QAeeO2UvoCSxqYhEj3Qb04o1ybpEVg4SMaAyoCoq+RXN2GWNhMQWgE/7wtcTz9Mpd5HNc2iCI0wUi8ABQWjn0GPch2mzPK5D0ny7Fg4/ob+wOIaVIgxJDGUDZaL48XkCXkYlBREhbyGyllQLdrzPtW9cdXiukUWV9GzP/PuknfiQN2IqzPb9RH7hyueHxiWBFJTPn/6VGkkt6fg72geFi6xJlUJBSdcSzGGc07zxJ7ct+7/5lFMvhl7UKhjsPEFeVMPScOYSyFFT8LlOdy4D6oUWbBxIZJ6X+G8NXMB5HGrXwt9rHM0BW4tTr9uYZiUk59ghQgDcyAiY8gE93HDNltEy6z0YxIB7pNvHx9k45xIu2AFczPPmhK/TlUFGaA3DwI2SgwqSlSdBm6sVIdbqaSas+eS2lqxZBM7UI7KgyEfQwygE4+fdfftj0XRtjUAaYtcKSWFFt6m0gz64oM8fE0bLB0k+MponrPI2ty20C3V9ekJ1+KzXvano6N960KA1Osu3mavDja7pbMWaGuvdnzNwiwlnFeVakcTHWUFXeqwZFFz5UeEwIwmTvgTdhJ1BPdp5c9Hs6T/I9g3nVI33SvQO/Xr85p/86AZdgABQeQr+qod+HRjSBWm7feMVbdwTyUklR9B8va5RMS6mzoejruDLLnSIg4=
    admin.passwordMtime: AgAHqKE6ejJpF30jBaTK32pU7mm310huhoxJgvCvmZs8ysJd1KzyTnMXX8dbQIe2Eaqf3BfEzo8noyQHQ8A4M+jxW8bFfY6SuABC4g+iVVPUMtNM8z0eZncB3u4FOhkFvBPKSLwaJVqafjYM+DjJZbbxl5nYAhk8X25tbjv5GM8TKAoz9FzwXhgXOWgg4WlhpGiXHQAWR25rWK42wWgi5/jn/2JY7ZiDNfItSIFnd/YsVpIL4EXghsnMiEcUXaaa+oY/pa5JAsUE7K0A9Els25z60AayeNiIuUk/chZMH5arl9xy8LbeCqgOFPqI94nbkqn9e/tmeCztcgUWTDHzzqo4dtfIhzQB6NvBpx2Ae18VJyo7qJZF3wIyAuq22lF05V/dsiwOWR3D3njevHApYT2n7XYAqUexZqR4NXbFbkJ1rpDDfYS6S8QqV5jTQ+EHlaD9VSfdGoEweUBi/NtZ4AvAhfys4IhgtBlvXY4hXTmBQ+G6U6tipcgcB4foWDa2i0ZLArNk+l+rR7Zb3ST4Ci5Tkdfj+LN5YexGrCHoiHUJ9qTo0WUuzjkNVGz/SGsBrK0Q0jUepIPm9g+1rwY8O+ObDHOj3IFNc1a6/QIP/fUcjigwTlcw0qma/HthFS7BF0MaaIQRl4X35dmR0kOWT+t01mj9Id8K9GceptxUPwrT9ISQv/8aDPjTiOO+vNWvExWk+MTW1UUJBf1ldDTgWUnIkzNeYOwf
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
